### ISSUE TITLE
Imagine Space

### ISSUE THREAD

**Issue by melissaroy** [coldfrontlabs/opl_vectorimages#10]
- [x] Make sure the meaning is well portrayed in the vector
- [x] Get approval / final edits

![screen shot 2016-11-07 at 1 53 46 pm](https://cloud.githubusercontent.com/assets/11425314/20071361/35e1aa6e-a4f2-11e6-870d-1940b8706b65.png)

**Comment by csimmons44** [comment]
Perhaps include also a person OR combine the imagery of a light bulb with a couple of pieces of technology. One of  them could be a telescope to show the less electronic tech side.

**Comment by melissaroy** [comment]
@csimmons44 

![screen shot 2016-11-11 at 9 29 08 am](https://cloud.githubusercontent.com/assets/11425314/20218194/52527a50-a7f1-11e6-8c5a-bb56aecaa9d3.png)
