### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by csimmons44** [coldfrontlabs/opl_vectorimages#12]
It could be mistaken for Business. I would remove the dollar sign and replace with a question mark. Our homework programs are for homework help mostly. What about Q  and A for Question  and Answer somewhere?

**Comment by melissaroy** [comment]
Let me know your opinion on the Q and A @csimmons44 

![screen shot 2016-11-07 at 3 47 53 pm](https://cloud.githubusercontent.com/assets/11425314/20075279/967d63a4-a501-11e6-95ee-04028ce0d4cc.png)
