### ISSUE TITLE
Home and gardening

### ISSUE THREAD

**Issue by csimmons44** [coldfrontlabs/opl_vectorimages#13]
Important to include the aspect of home too.  A window with a garden (indistinguishable between balcony or yard) would be ideal.

**Comment by melissaroy** [comment]
Added home and reduced gardening size. @csimmons44 

![screen shot 2016-11-07 at 3 41 55 pm](https://cloud.githubusercontent.com/assets/11425314/20075084/cec77c8c-a500-11e6-837d-788963ccd72b.png)
