### ISSUE TITLE
Hobbies & Crafts

### ISSUE THREAD

**Issue by melissaroy** [coldfrontlabs/opl_vectorimages#2]
- [x] Remove a bobby spin
- [x] Add a "craft" element (glue stick maybe beads?)
- [ ] Get approval / final edits

![screen shot 2016-11-07 at 12 23 42 pm](https://cloud.githubusercontent.com/assets/11425314/20067984/14427238-a4e5-11e6-95be-7401b1a2f47a.png)

**Comment by csimmons44** [comment]
Lot of knitting programs so that could help. Glue stick sounds good.

**Comment by melissaroy** [comment]
Removed a few sewing items and added marker + glue @csimmons44 

![screen shot 2016-11-07 at 3 48 49 pm](https://cloud.githubusercontent.com/assets/11425314/20075309/b770a33c-a501-11e6-89eb-776efee5a2c9.png)
