### ISSUE TITLE
Travel

### ISSUE THREAD

**Issue by melissaroy** [coldfrontlabs/opl_vectorimages#6]
- [x] Make airplane appear closer to earth.
- [ ] Get approval / final edits

![screen shot 2016-11-07 at 12 37 02 pm](https://cloud.githubusercontent.com/assets/11425314/20068483/f09d2c72-a4e6-11e6-8336-1df3fbacc90a.png)

**Comment by csimmons44** [comment]
Could just switch the sky to blue with clouds so its less spacelike?

**Comment by melissaroy** [comment]
@csimmons44 

![screen shot 2016-11-11 at 9 28 00 am](https://cloud.githubusercontent.com/assets/11425314/20218170/38f7cfa6-a7f1-11e6-93bc-c44780b4578b.png)
